import React, { useState } from 'react';
import { 
  X, Copy, Check, Printer, FileText, Download, FileDown 
} from 'lucide-react';
import type { RevisionPack } from '../../types/revision';

interface ExportModalProps {
  pack: RevisionPack;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  pack,
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = (): string => {
    let md = `# KURIO Revision Pack: ${pack.metadata.title}\n`;
    md += `**Subject:** ${pack.metadata.subject} | **Slides/Pages:** ${pack.metadata.total_pages_detected} | **Est. Study Time:** ${pack.metadata.estimated_study_time_mins} mins\n`;
    md += `*Grounded academic synthesis generated by KURIO*\n\n`;
    
    md += `## 1. Executive Overview\n`;
    md += `${pack.executive_summary.overview}\n\n`;
    
    if (pack.key_concepts && pack.key_concepts.length > 0) {
      md += `### Core Vocabulary & Key Concepts\n`;
      pack.key_concepts.forEach((c) => {
        md += `- **${c.name}**: ${c.definition} *(Why: ${c.importance_summary})*\n`;
      });
      md += `\n`;
    }

    md += `### Core Takeaways\n`;
    pack.executive_summary.key_takeaways.forEach((t, i) => {
      md += `${i + 1}. ${t}\n`;
    });
    md += `\n`;

    md += `### Foundational Prerequisites\n`;
    pack.executive_summary.foundational_prerequisites.forEach((p) => {
      md += `- ${p}\n`;
    });
    md += `\n---\n\n`;

    md += `## 2. High-Priority Revision Topics\n\n`;
    pack.high_priority_topics.forEach((topic, idx) => {
      md += `### Topic ${idx + 1}: ${topic.title} [Priority: ${topic.priority}]\n`;
      if (topic.source_page) md += `*Source: Slide/Page ${topic.source_page}*\n`;
      md += `**Why High Priority:** ${topic.why_important}\n\n`;
      md += `${topic.core_summary}\n\n`;
      if (topic.key_formulas_or_rules && topic.key_formulas_or_rules.length > 0) {
        md += `**Key Formulations:**\n`;
        topic.key_formulas_or_rules.forEach((r) => md += `- \`${r}\`\n`);
        md += `\n`;
      }
    });
    md += `---\n\n`;

    md += `## 3. Common Confusion Points\n\n`;
    pack.common_confusion_points.forEach((c) => {
      md += `### ${c.concept_a} vs. ${c.concept_b}\n`;
      md += `**Context:** ${c.topic_ref}\n`;
      md += `**Definitive Distinction:** ${c.key_distinction}\n`;
      md += `**Common Misconception:** ${c.common_misconception}\n\n`;
    });
    md += `---\n\n`;

    md += `## 4. Active-Recall Flashcards\n\n`;
    pack.flashcards.forEach((f, idx) => {
      md += `**Card ${idx + 1}:** ${f.front}\n`;
      md += `> **Answer:** ${f.back}\n\n`;
    });

    return md;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const sanitizedTitle = pack.metadata.title.toLowerCase().replace(/[^a-z0-9]/g, '_');
    link.href = url;
    link.setAttribute('download', `kurio_revision_${sanitizedTitle}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm no-print animate-fade-in">
      
      <div className="relative w-full max-w-lg glass-panel rounded-2xl p-6 border border-surface-700 shadow-2xl space-y-6">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-surface-800">
          <div className="flex items-center space-x-2.5">
            <div className="h-8 w-8 rounded-lg bg-brand-500/20 text-brand-400 flex items-center justify-center">
              <Download className="h-4 w-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">
                Download Revision Pack
              </h3>
              <p className="text-xs text-slate-400">
                Save for offline study, Notion, or physical exam prep
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Options */}
        <div className="space-y-3">
          
          {/* Download Markdown File */}
          <div className="p-4 rounded-xl bg-surface-900 border border-surface-800 flex items-center justify-between">
            <div className="space-y-0.5">
              <div className="text-xs font-semibold text-white flex items-center space-x-1.5">
                <FileDown className="h-3.5 w-3.5 text-brand-400" />
                <span>Download Markdown File (.md)</span>
              </div>
              <p className="text-[11px] text-slate-400">
                Download ready-to-use markdown notes directly to your device
              </p>
            </div>

            <button
              onClick={handleDownloadFile}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-brand-600 hover:bg-brand-500 text-white transition-all flex items-center space-x-1 shadow-md shadow-brand-500/20"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download</span>
            </button>
          </div>

          {/* Copy Markdown to Clipboard */}
          <div className="p-4 rounded-xl bg-surface-900 border border-surface-800 flex items-center justify-between">
            <div className="space-y-0.5">
              <div className="text-xs font-semibold text-white flex items-center space-x-1.5">
                <FileText className="h-3.5 w-3.5 text-indigo-400" />
                <span>Copy Markdown to Clipboard</span>
              </div>
              <p className="text-[11px] text-slate-400">
                Quick copy for Notion, Obsidian, and markdown editors
              </p>
            </div>

            <button
              onClick={handleCopyMarkdown}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-surface-850 hover:bg-surface-800 text-slate-200 border border-surface-700 transition-all flex items-center space-x-1"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>
          </div>

          {/* Print / Save to PDF */}
          <div className="p-4 rounded-xl bg-surface-900 border border-surface-800 flex items-center justify-between">
            <div className="space-y-0.5">
              <div className="text-xs font-semibold text-white flex items-center space-x-1.5">
                <Printer className="h-3.5 w-3.5 text-emerald-400" />
                <span>Print or Save to PDF</span>
              </div>
              <p className="text-[11px] text-slate-400">
                High-contrast, distraction-free study layout
              </p>
            </div>

            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-surface-850 hover:bg-surface-800 text-slate-200 transition-all flex items-center space-x-1 border border-surface-700"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print</span>
            </button>
          </div>

        </div>

        {/* Footer */}
        <div className="pt-2 text-center text-[11px] text-slate-400">
          KURIO Revision Pack &bull; Formatted for rapid exam review
        </div>

      </div>

    </div>
  );
};
